---
version: 2.1
jobs:
  list-updated:
    docker: 
    - image: alpine:3.10.3
    steps:
    - run:
        name: install candy
        command: |
          # Error uploading workspace archive: RequestError: send request failed
          # x509: certificate signed by unknown authority
          apk add ca-certificates curl git
          curl -o /tmp/candy.tar.gz -L https://github.com/suzuki-shunsuke/candy/releases/download/v0.1.0-0/candy_0.1.0-0_linux_amd64.tar.gz
          tar xvzf /tmp/candy.tar.gz -C /tmp
          chmod a+x /tmp/candy
    - checkout
    - run:
        name: list updated services
        command: |
          /tmp/candy list-updated > updated.txt
          cat updated.txt
    - persist_to_workspace:
        root: .
        paths:
        - "*"
  build-foo:
    docker: 
    - image: &image_go golang:1.13.4
    steps:
    - attach_workspace:
        at: .
    - run:
        name: build foo
        command: bash foo/build.sh
  build-bar:
    docker: 
    - image: *image_go
    steps:
    - attach_workspace:
        at: .
    - run:
        name: build bar
        command: bash bar/build.sh
workflows:
  build:
    jobs:
    - list-updated
    - build-foo:
        requires:
        - list-updated
    - build-bar:
        requires:
        - list-updated
