---
version: 2.1
jobs:
  list-updated:
    docker: 
    - image: alpine:3.10.3
    steps:
    - checkout
    - run: |
        # Error uploading workspace archive: RequestError: send request failed
        # x509: certificate signed by unknown authority
        apk add ca-certificates
        sh bin/candy list-updated > updated.txt
    - persist_to_workspace:
        root: .
        paths:
        - "*"
  build-foo:
    docker: 
    - image: &image_go golang:1.13.4
    steps:
    - attach_workspace:
        at: .
    - run: bash foo/build.sh
  build-bar:
    docker: 
    - image: *image_go
    steps:
    - attach_workspace:
        at: .
    - run: bash bar/build.sh
workflows:
  build:
    jobs:
    - list-updated
    - build-foo:
        requires:
        - list-updated
    - build-bar:
        requires:
        - list-updated
